### ISSUE TITLE
Have Travis display details on test failure

### ISSUE THREAD

**Issue by PLNech** [algolia/algoliasearch-client-android#33]
Turning this:

> 	junit.framework.AssertionFailedError at com.algolia.search.saas.ApplicationTest.testAddObjectAsync(ApplicationTest.java:131)

into this:

> 	junit.framework.AssertionFailedError: **Object has unexpected objectId**
> at com.algolia.search.saas.ApplicationTest$10Listener.getObjectsResult(ApplicationTest.java:319)
>...

**Comment by PLNech** [comment]
Fixed in #122.
