### ISSUE TITLE
Parcel.java

### ISSUE THREAD

**Issue by PankajS24** [algolia/algoliasearch-client-android#581]
I have been getting a few exception in the parcel class. I have traced it down to Algolia Android Client.
**This issue is specifically started coming in Android 8**
Unfortunately I have these logs only

`Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:365)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
       at java.util.concurrent.FutureTask.run(FutureTask.java:271)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)`

**Comment by spinach** [comment]
Hello @PankajS24, thank you for contacting us. 

Unfortunately it is very hard to debug the error with the following stack trace, as there isn't a lot of information. Is there a way that you can give us the steps to reproduce your issue? Or any way you can get more logs ?
