### ISSUE TITLE
_requestRaw does not close `stream`

### ISSUE THREAD

**Issue by yukuku** [algolia/algoliasearch-client-android#93]
Android StrictMode reports:

```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
java.lang.Throwable: Explicit termination method 'end' not called
    at dalvik.system.CloseGuard.open(CloseGuard.java:180)
    at java.util.zip.Inflater.<init>(Inflater.java:82)
    at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
    at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
    at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
    at com.algolia.search.saas.Client._requestRaw(Client.java:697)
    at com.algolia.search.saas.Client.postRequestRaw(Client.java:545)
    at com.algolia.search.saas.Index.searchRaw(Index.java:870)
    at com.algolia.search.saas.Index.search(Index.java:847)
    at com.algolia.search.saas.Index.searchSync(Index.java:135)

```

It is because the `stream` is not closed on `Client.java`.

**Comment by PLNech** [comment]
Hi @yukuku, thank you for your report! 
We improved the handling of open resources in #94 and will ship this change with the next minor release.

**Comment by PLNech** [comment]
[Version 3.2.2](https://github.com/algolia/algoliasearch-client-android/releases/tag/3.2.2) has been released with the aforementioned fix.
